[project]
site_name = "QualCoder"  
site_url = "https://qualcoder.org/"  
site_description = "QualCoder Website"  
site_author = "QualCoder Teams"  
docs_dir = "docs"  
repo_url = "https://github.com/QualCoder-Org/qualcoder-org.github.io"  
repo_name = "QualCoder-Org/qualcoder-org.github.io"  
edit_uri = "edit/main/docs/"  
extra_css = ["stylesheets/extra.css"]
#  [project.markdown_extensions.attr_list]
#[project.markdown_extensions.md_in_html]
#[project.markdown_extensions.pymdownx.emoji]
#emoji_generator = "zensical.extensions.emoji.to_svg"  
#emoji_index = "zensical.extensions.emoji.twemoji"
#[project.markdown_extensions.admonition]
#[project.markdown_extensions.pymdownx.details]
#[project.markdown_extensions.pymdownx.superfences]
#[project.markdown_extensions.pymdownx.tabbed]
#
alternate_style = true  
combine_header_slug = true  


nav = [  
	{"Home" = "index.md"},  
	# {"Blog" = "https://qualcoder.wordpress.com/"},  
	{"Blog" = "blog/index.md"},  
	{"Documentation" = "doc/index.md"},  
	{"Resources" = [  
		"ressources.md",  
		"videos.md",  
		"using.md"  
	]},  
	{"Team" = "about.md"},  
	{"Community" = "community.md"},  
	{"en" = [
		"doc/en/index.md",  
		"doc/en/1.-Overview.md",
		{"Setup" = [
				"doc/en/2.1.-Installation.md",  
				"doc/en/2.2.-Settings.md",  
				"doc/en/2.3.-AI-Setup.md",  
				"doc/en/2.4.-Working-in-a-Team.md"
		]},
		{"Managing Data" = [
				"doc/en/3.1.-Creating-a-New-Project.md",  
				"doc/en/3.2.-Files.md",  
				"doc/en/3.3.-Cases.md",  
				"doc/en/3.4.-Attributes.md",
				"doc/en/3.5.-References.md"
		]},
		{"Coding" = [
			"doc/en/4.1.-Coding-Text.md",  
			"doc/en/4.2.-AI-Assisted-Coding.md",  
			"doc/en/4.3.-Coding-Text-on-PDFs.md",  
			"doc/en/4.4.-Coding-Images.md",  
			"doc/en/4.5.-Coding-Audio-and-Video.md",  
			"doc/en/4.6.-Code-Organiser.md",
			"doc/en/4.7.-Codes-Tree.md"
		]},
		{"Analyzing the Results" = [
			"doc/en/5.1.-AI-chat-based-analysis.md",  
			"doc/en/5.2.-Journals.md", 
			"doc/en/5.3.-Analysis.md",
			"doc/en/5.4.-Reports.md",  
			"doc/en/5.5.-Graph.md"
		]},
		{"Advanced Options" = [
			"doc/en/6.1.-Imports-and-Exports.md",  
			"doc/en/6.2.-AI-Prompt-Library.md"
		]},
		{"Other Information" = [
			"doc/en/7.3.-QualCoder-Development.md",  
			"doc/en/7.4.-SQlite-Data-Structure.md",  
			"doc/en/7.5.-AI-Technical-Information.md",  
			"doc/en/7.6.-How-to-contribute.md"
		]}
	]},  
	{"fr" = [
		"doc/fr/index.md",  
		"doc/fr/1.-Overview.md",
		{"Démarrer" = [
				"doc/fr/2.1.-Installation.md",  
				"doc/fr/2.2.-Settings.md",  
				"doc/fr/2.3.-AI-Setup.md",  
				"doc/fr/2.4.-Working-in-a-Team.md"
		]},
		{"Gérer les données" = [
				"doc/fr/3.1.-Creating-a-New-Project.md",  
				"doc/fr/3.2.-Files.md",  
				"doc/fr/3.3.-Cases.md",  
				"doc/fr/3.4.-Attributes.md",
				"doc/fr/3.5.-References.md"
		]},
		{"Coder" = [
			"doc/fr/4.1.-Coding-Text.md",  
			"doc/fr/4.2.-AI-Assisted-Coding.md",  
			"doc/fr/4.3.-Coding-Text-on-PDFs.md",  
			"doc/fr/4.4.-Coding-Images.md",  
			"doc/fr/4.5.-Coding-Audio-and-Video.md",  
			"doc/fr/4.6.-Code-Organiser.md",
			"doc/fr/4.7.-Codes-Tree.md"
		]},
		{"Analyser" = [
			"doc/fr/5.1.-AI-chat-based-analysis.md",  
			"doc/fr/5.2.-Journals.md", 
			"doc/fr/5.3.-Analysis.md",
			"doc/fr/5.4.-Reports.md",  
			"doc/fr/5.5.-Graph.md"
		]},
		{"Options avancées" = [
			"doc/fr/6.1.-Imports-and-Exports.md",  
			"doc/fr/6.2.-AI-Prompt-Library.md"
		]},
		{"Informations complémentaires" = [
			"doc/fr/7.3.-QualCoder-Development.md",  
			"doc/fr/7.4.-SQlite-Data-Structure.md",  
			"doc/fr/7.5.-AI-Technical-Information.md",  
			"doc/fr/7.6.-How-to-contribute.md"
		]}
	]},  
	{"es" = [
		"doc/es/index.md",  
		"doc/es/1.-Overview.md",
		{"Setup" = [
				"doc/es/2.1.-Installation.md",  
				"doc/es/2.2.-Settings.md",  
				"doc/es/2.3.-AI-Setup.md",  
				"doc/es/2.4.-Working-in-a-Team.md"
		]},
		{"Managing Data" = [
				"doc/es/3.1.-Creating-a-New-Project.md",  
				"doc/es/3.2.-Files.md",  
				"doc/es/3.3.-Cases.md",  
				"doc/es/3.4.-Attributes.md" 
		]},
		{"Coding" = [
			"doc/es/4.1.-Coding-Text.md",  
			"doc/es/4.2.-AI-Assisted-Coding.md",  
			"doc/es/4.3.-Coding-Text-on-PDFs.md",  
			"doc/es/4.4.-Coding-Images.md",  
			"doc/es/4.5.-Coding-Audio-and-Video.md",  
			"doc/es/4.6-Code-Organiser.md"
		]},
		{"Analyzing the Results" = [
			"doc/es/5.1.-AI-chat-based-analysis.md",  
			"doc/es/5.2.-Journals.md",  
			"doc/es/5.3.-Reports.md",  
			"doc/es/5.4.-Graph.md"
		]},
		{"Advanced Options" = [
			"doc/es/6.1.-Imports-and-Exports.md",  
			"doc/es/6.2.-AI-Prompt-Library.md"
		]},
		{"Other Information" = [
			"doc/es/7.3.-QualCoder-Development.md",  
			"doc/es/7.4.-SQlite-Data-Structure.md",  
			"doc/es/7.5.-AI-Technical-Information.md",  
			"doc/es/7.6.-How-to-contribute.md"
		]}
	]},  
	{"de" = [
		"doc/de/index.md",  
		"doc/de/1.-Overview.md",
		{"Setup" = [
				"doc/de/2.1.-Installation.md",  
				"doc/de/2.2.-Settings.md",  
				"doc/de/2.3.-AI-Setup.md",  
				"doc/de/2.4.-Working-in-a-Team.md"
		]},
		{"Managing Data" = [
				"doc/de/3.1.-Creating-a-New-Project.md",  
				"doc/de/3.2.-Files.md",  
				"doc/de/3.3.-Cases.md",  
				"doc/de/3.4.-Attributes.md" 
		]},
		{"Coding" = [
			"doc/de/4.1.-Coding-Text.md",  
			"doc/de/4.2.-AI-Assisted-Coding.md",  
			"doc/de/4.3.-Coding-Text-on-PDFs.md",  
			"doc/de/4.4.-Coding-Images.md",  
			"doc/de/4.5.-Coding-Audio-and-Video.md",  
			"doc/de/4.6-Code-Organiser.md"
		]},
		{"Analyzing the Results" = [
			"doc/de/5.1.-AI-chat-based-analysis.md",  
			"doc/de/5.2.-Journals.md",  
			"doc/de/5.3.-Reports.md",  
			"doc/de/5.4.-Graph.md"
		]},
		{"Advanced Options" = [
			"doc/de/6.1.-Imports-and-Exports.md",  
			"doc/de/6.2.-AI-Prompt-Library.md"
		]},
		{"Other Information" = [
			"doc/de/7.3.-QualCoder-Development.md",  
			"doc/de/7.4.-SQlite-Data-Structure.md",  
			"doc/de/7.5.-AI-Technical-Information.md",  
			"doc/de/7.6.-How-to-contribute.md"
		]}
	]},
	{"pt" = ["doc/pt/index.md"]},
	{"sv" = ["doc/sv/index.md"]},
	{"zh" = ["doc/zh/index.md"]},
	{"ja" = ["doc/ja/index.md"]},
	{"ro" = ["doc/ro/index.md"]},
	{"it" = ["doc/it/index.md"]},
	{"ht" = ["doc/ht/index.md"]},
	{"eu" = ["doc/eu/index.md"]},
	{"fa" = ["doc/fa/index.md"]},
	{"eo" = ["doc/eo/index.md"]},
	{"oc" = ["doc/oc/index.md"]}
]
  
[project.theme]
variant = "modern"  
logo = "images/logo.png"  
custom_dir = "overrides"
features = [  
#  "content.action.edit",  
#  "content.action.view",  
#  "navigation.sections",
#  "navigation.expand",
#  "navigation.tabs",
#  "navigation.path",  
#  "navigation.indexes",
#  "toc.follow",
#  "toc.integrate",  
#  "search.highlight",  
#  "navigation.tabs",  
#  "navigation.footer",  
#  "content.tabs.link"  
  "announce.dismiss",
  "content.action.edit",
  "content.action.view",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  "navigation.footer",
  "navigation.indexes",
  "navigation.path",
  "navigation.sections",
  "navigation.tabs",
  "navigation.top",
  "search.highlight"
]
  
[[project.theme.palette]]
scheme = "default"  
media = "(prefers-color-scheme: light)"  
toggle.icon = "lucide/sun"  
toggle.name = "Switch to dark mode"  
  
[[project.theme.palette]]
scheme = "slate"  
media = "(prefers-color-scheme: dark)"  
toggle.icon = "lucide/moon"  
toggle.name = "Switch to light mode"  
  
[project.extra]
alternate = [  
    { name = "English", link = "/doc/en/", lang = "en" },  
    { name = "Deutsch", link = "/doc/de/", lang = "de" },
    { name = "Español", link = "/doc/es/", lang = "es" },  
    { name = "Français", link = "/doc/fr/", lang = "fr" },
	{ name = "Esperanto", link = "doc/eo/", lang = "eo" },
	{ name = "Euskara", link = "/doc/eu/", lang = "eu" },
	{ name = "Italiano", link = "/doc/it/", lang = "it" },
	{ name = "Kreyòl ayisyen", link="/doc/ht/", lang = "ht"},
	{ name = "Occitan", link = "/doc/eo/", lang = "eo" },
	{ name = "Português", link = "/doc/pt/", lang = "pt" },
	{ name = "Română", link = "/doc/ro/", lang = "ro" },
	{ name = "Svenska", link = "/doc/sv/", lang = "sv" },
	{ name = "فارسی", link = "doc/fa/", lang = "fa" },
	{ name = "中文", link = "/doc/zh/", lang = "zh" },
	{ name = "日本語", link = "/doc/ja/", lang = "ja" }
]
